server:
  port: 8080

spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/spring_study
        username: root
        password: root

        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    servlet:
        multipart:
            max-file-size: 128KB
            max-request-size: 128KB
            enabled: true #默认允许上传文件，如果要禁用，把些属改为false
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.weison.model
  configLocation: classpath:/mybatis-config.xml

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql